const driverBirthPlaces = {
  kevin_magnussen: 'Roskilde, Denmark',
  leclerc: 'Monte Carlo, Monaco',
  sainz: 'Madrid, Spain',
  hamilton: 'Stevenage, England',
  russell: "King's Lynn, England",
  bottas: 'Nastola, Finland',
  ocon: 'Évreux, Normandy',
  tsunoda: 'Sagamihara, Japan',
  alonso: 'Oviedo, Spain',
  zhou: 'Shanghai, China',
  mick_schumacher: 'Vufflens-le-Château, Switzerland',
  stroll: 'Montreal, Canada',
  albon: 'London, England',
  ricciardo: 'Perth, Australia',
  norris: 'Bristol, England',
  latifi: 'Montreal, Canada',
  hulkenberg: 'Emmerich, Germany',
  perez: 'Guadalajara, Mexico',
  max_verstappen: 'Hasselt, Belgium',
  gasly: 'Rouen, France',
  vettel: 'Heppenheim, Germany',
  de_vries: 'Uitwellingerga, Netherlands',
  sargenat: 'Fort Lauderdale, Florida',
  piastri: 'Melbourne, Victoria',
  lawson: 'Hastings, New Zealand',
  bearman: 'Chelmsford, UK',
  'colapinto ': 'Buenos Aires, Argentina',
  colapinto: 'Buenos Aires, Argentina',
};
export default driverBirthPlaces;
