name: Github Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.3.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build
        env:
          CI: 'false'

  codacy-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug Codacy Token
        run: |
          echo "Token length: ${#CODACY_PROJECT_TOKEN}"
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

      - name: Install Codacy CLI
        run: |
          curl -Ls https://coverage.codacy.com/get.sh | bash
          chmod +x codacy-coverage-reporter

      - name: Run Codacy Analysis
        run: |
          ./codacy-coverage-reporter analyze -t ${{ secrets.CODACY_PROJECT_TOKEN }} -r .
        # env:
        #   CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
